### ISSUE TITLE
Handle object in multiValues

### ISSUE THREAD

**Issue by lauterry** [ptgolden/immfacet#3]
Hi

Given the following nested data : 

```
const nestedData = Immutable.fromJS([
  { person: { name: 'Diz', favorite_things: [{name: 'lemonade', price: 12}]  }},
  { person: { name: 'Grizz', favorite_things: [{name: 'lemonade', price: 12},  {name:'lollipops', price: 23}}},
  { person: { name: 'Liz', favorite_things: [{name: 'ice'}]}}
])
```

How can I get the following facets by index: 

```
Immutable.Map({
      'person.favorite_things.label': Immutable.Map({
        'lemonade': Immutable.Set([0, 1]),
        'lollipops': Immutable.Set([1]),
        'ice': Immutable.Set([2])
      })
    })
```

I know how to handle when ```favorite_things``` is an array of String but what if ```favorite_things``` is an array of object ?

Best regards

**Comment by ptgolden** [comment]
The dot notation of of 'addFieldFacet' can only access directly nested fields. In this case, running:
```js
item.getIn(['person', 'favorite_things', 'label'])
```
on any of those items will return `undefined`. To actually return the name, you would need to run, e.g.:
```js
item.getIn(['person', 'favorite_things', 0, 'label'])
```

There are two things you could do. First, you could just use `person.favorite_things` as the field to facet on, which will effectively give you what you're looking for, although with the facet values `Map({ name: 'lemonade', price: 12 })` rather than just the string `lemonade`. This is possible because facet values are calculated based on comparison with `Immutable.is` rather than `===`.

The other thing you could do is write your own function on which to calculate the facet rather than relying on the `addFieldFacet` convenience method.

```js
function getFavoriteThingNames(item) {
  return item.getIn(['person', 'favorite_things']).map(thing => thing.get('name'))
}

let fc = new FacetedClassification(nestedData)
fc = fc.addFacet('favoriteThingNames', getFavoriteThingNames, { multiValue: true })

console.log(fc.facetsByIndex())
/*
Immutable.Map({
 'favoriteThingNames': Immutable.Map({
    'lemonade': Immutable.Set([0, 1]),
    'lollipops': Immutable.Set([1]),
    'ice': Immutable.Set([2])
  })
})
*/
```

That will give you the result you asked about, with strings as the facet values.

Hope that helps!

**Comment by lauterry** [comment]
Hi @ptgolden 

I've ended up writing my own function using `addFacet` (the second solution you suggested).

and this works very well.

Best regards
